# Generated by Django 3.2.5 on 2021-07-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('bug_desc', models.CharField(max_length=200)),
                ('bug_status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Bug_Table',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_desc', models.CharField(max_length=200)),
                ('project_team', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Project_Table',
            },
        ),
    ]
